version: '3.7'
services:
  database:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: senha001
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: wasabisushi
    volumes:
      - ./db:/docker-entrypoint-initdb.d